name: desafio_salaryfits
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  http: ^1.0.0
  geolocator: ^9.0.2
  fl_chart: ^0.63.0
  intl: ^0.18.0
  localstorage: ^4.0.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.1
  mocktail: ^0.3.0
  faker: ^2.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
